<?php
set_include_path( get_include_path() . PATH_SEPARATOR . $_SERVER['DOCUMENT_ROOT'] );
date_default_timezone_set('America/Detroit');
?>

<!doctype html>
<html lang="en-US">
  <!-- generated by uswds@2.7.0 -->
  <head>
    <?php
      include("assets/includes/meta.inc");
    ?>
    <title>Join your Local OPC branch</title>
    <?php
      include("assets/includes/css.inc");
    ?>
  </head>
  <body>

    <?php
      include("assets/includes/banner.inc");
      include("assets/includes/header-info.inc");
    ?>
    
    <!-- Start -->
    <div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          
          <!-- Side Nav -->
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>">Home</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>new-contracts/" class="">New Contracts</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>register-to-vote/" class="">Register To Vote</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>report-all-cops/" class="">Report All Cops</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>resources/" class="">Resources</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>support/" class="">Support</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>join/" class="usa-current">Join your Local OPC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>contact/" class="">Contact us</a></li>
              </ul>
            </nav>
          </div>
          
          <!-- Main -->
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>In Union, there is Strength</h1>
            <p class="usa-intro">Build the bonds of your community.</p>
            <p>Join others who are interested in starting a branch in your community or be the first to start one yourself. Gather the information, analyze it, use it for the purpose of getting engaged, and make a difference in your community! Either way, you'll have our help, materials, and expertise. Use this form to let us know your interest and we'll make sure to connect you with others in your neighborhood hoping to work with you. If you do not see a form below, please <a href="https://forms.gle/upHo3HmM6pEAy1MD9" alt="" target="_blank" rel="noopener noreferrer">use this link</a>.</p>
            <p>
              <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScClMUXCiJTu5CSdLQNp31SkJkz92BluGBTQOtiyB68_AOmuA/viewform?embedded=true" width="640" height="2190" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
            </p>
          </main>
        </div>
      </div>
    </div>
    
    <!-- Fin! -->
    <?php
      include("assets/includes/footer.inc");
      include("assets/includes/scripts.inc");
    ?>
  </body>
</html>
