<?php
set_include_path( get_include_path() . PATH_SEPARATOR . $_SERVER['DOCUMENT_ROOT'] );
date_default_timezone_set('America/Detroit');
?>

<!doctype html>
<html lang="en-US">
  <!-- generated by uswds@2.7.0 -->
  <head>
    <?php
      include("assets/includes/meta.inc");
    ?>
    <title>Register to vote and be heard</title>
    <?php
      include("assets/includes/css.inc");
    ?>
  </head>
  <body>

    <?php
      include("assets/includes/banner.inc");
      include("assets/includes/header-local.inc");
    ?>
    
    <!-- Beginning -->
    <div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          
          <!-- Side Nav -->
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>">Home</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/new-contracts/" class="">New Contracts</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/register-to-vote/" class="usa-current">Register To Vote</a>
                  <ul class="usa-sidenav__sublist">
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>/register-to-vote/">Be heard by power</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>/register-to-vote/#register-to-vote">How to register today</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>/register-to-vote/#improve-voting">Improve access to voting</a></li>
                  </ul>
                </li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/report-all-cops/" class="">Report All Cops</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/resources/" class="">Resources</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/support/" class="">Support</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/join/" class="">Join your Local OPC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/contact/" class="">Contact us</a></li>
              </ul>
            </nav>
          </div>
          
          <!-- Main -->
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Be heard in the halls of power</h1>
            <p class="usa-intro">Support politicians that support you.</p>
            
            <!-- Register -->
            <h2 id="register-to-vote">Register to vote</h2>
            <p>There is no better way to find out how to register to vote in your state than using the official website run by the US government, <a href="https://vote.gov/" alt="" target="_blank" rel="noopener noreferrer">vote.gov</a>. Voting is important for more than just Presidential elections - true change comes from participation in local elections.</p>
            <p>Local judges, some police chiefs and prosecutors, and all the key decision-makers who negotiate police contracts and who will decide what police can legally do to you are all elected in non-Presidential ballots.</p>
            <p>Find out <a href="https://ballotpedia.org/Main_Page" alt="" target="_blank" rel="noopener noreferrer">when and who is running</a> in your next community election.</p>
            
            <!-- Improve access -->
            <h2 id="improve-voting">Improve access to voting</h2>
            <p>There are a five states (Colorado, Hawaii, Oregon, Washington and Utah) that allow <a href="https://www.ncsl.org/research/elections-and-campaigns/all-mail-elections.aspx" alt="" target="_blank" rel="noopener noreferrer">all-mail elections</a> (otherwise known as vote-by-mail), with 21 others that provide vote-by-mail for smaller elections. Additionally, all states have some form of <a href="https://www.ncsl.org/research/elections-and-campaigns/absentee-and-early-voting.aspx" alt="" target="_blank" rel="noopener noreferrer">absentee ballots and early voting</a> available to voters, but there is room to expand this - including the creation of a <a href="https://en.wikipedia.org/wiki/Election_Day_(United_States)" alt="" target="_blank" rel="noopener noreferrer">holiday for Election Day</a>.</p>
            <p>Contact your <a href="https://www.usa.gov/election-office" alt="" target="_blank" rel="noopener noreferrer">local election officials</a> to see if you can implement vote-by-mail, early voting, and absentee ballots for the smallest elections possible, and scale up from there. If you can get official support all the way up to the county level, you have a chance of changing the laws in your state!</p>
          </main>
        </div>
      </div>
    </div>
    
    <!-- Fin! -->
    <?php
      include("assets/includes/footer.inc");
      include("assets/includes/scripts.inc");
    ?>
  </body>
</html>
