<?php
set_include_path( get_include_path() . PATH_SEPARATOR . $_SERVER['DOCUMENT_ROOT'] );
date_default_timezone_set('America/Detroit');
?>

<!doctype html>
<html lang="en-US">
  <!-- generated by uswds@2.7.0 -->
  <head>
    <?php
      include("assets/includes/meta.inc");
    ?>
    <title>Report good and bad cops to the public</title>
    <?php
      include("assets/includes/css.inc");
    ?>
  </head>
  <body>

    <?php
      include("assets/includes/banner.inc");
      include("assets/includes/header-local.inc");
    ?>

    <!-- Beginning -->
    <div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          
          <!-- Side Nav -->
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>">Home</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/new-contracts/" class="">New Contracts</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/register-to-vote/" class="">Register To Vote</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/report-all-cops/" class="usa-current">Report All Cops</a>
                  <ul class="usa-sidenav__sublist">
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>/report-all-cops/">What it takes to be heard</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>/report-all-cops/#share-everything">Share the good and bad</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>/report-all-cops/#why-this-matters">Why this matters to you</a></li>
                  </ul>
                </li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/resources/" class="">Resources</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/support/" class="">Support</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/join/" class="">Join your Local OPC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>/contact/" class="">Contact us</a></li>
              </ul>
            </nav>
          </div>
          
          <!-- Main -->
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Support good cops who can't speak</h1>
            <p class="usa-intro">The eye of justice are blind, but not everyone has a voice.</p>
            
            <!-- Share everything -->
            <h2 id="share-everything">Share the good and bad</h2>
            <p>It is important to not only share the stories of negative interactions, but also those that are positive. Ensuring those that set a good example are promoted through the ranks is how those same individuals will serve as role models for others, while also ensuring they are protected from potential retaliation. In those situations where an officer (or officers, including those who simply stand by and watch) does wrong, make sure you record the interaction. While the <a href="https://www.aclu.org/issues/criminal-law-reform/reforming-police/aclu-apps-record-police-conduct" alt="" target="_blank" rel="noopener noreferrer">ACLU has made an app for some states</a>, with <a href="https://www.nolo.com/legal-encyclopedia/recording-the-police-legal.html" alt="" target="_blank" rel="noopener noreferrer">NOLO making a guide for others</a>.
            <p>Whether you submit something through an online form or with a hard copy in the mail, save a copy of your submission and consider <a href="https://www.usatoday.com/in-depth/news/investigations/2019/04/24/biggest-collection-police-accountability-records-ever-assembled/2299127002/" alt="" target="_blank" rel="noopener noreferrer">sharing it with the public</a>. USA Today collected the largest group of misconduct records</a> ever assembled, finding 30,000+ that were banned, but even more that were disciplined but able to continue working in another jurisdiction.</p>
            <p>Unfortunately, it is often only when a story is picked up by the media that something will happen. We need to change that. Reinforce the values and culture of our communities through constant communication with our local governments.</p>
            <p>These are links to the complaint and compliment forms that you can use to be heard:
              <ul>
                <li>Albuquerque, New Mexico
                  <ul>
                    <li><a href="https://www.cabq.gov/cpoa/albuquerque-police-complaint-or-commendation-form/how-to-file-a-police-complaint-or-commendation" alt="" target="_blank" rel="noopener noreferrer">Instructions, paper forms, and an online form</a>.</li>
                  </ul>
                </li>
                <li>Anaheim, California
                  <ul>
                    <li><a href="https://www.anaheim.net/2495/Customer-Service" alt="" target="_blank" rel="noopener noreferrer">Instructions, paper forms, and an online form</a>.</li>
                  </ul>
                </li>
                <li>Anchorage, Alaska
                  <ul>
                    <li><a href="https://www.muni.org/departments/police/howdoi/documents/apd%201095%20ver.%205_12.pdf" alt="" target="_blank" rel="noopener noreferrer">Instructions</a> <img src="assets/images/pdf.png" alt="Icon of a PDF file created by Freepik on Flaticon.com." class="icon-pdf" />, <a href="https://www.muni.org/departments/police/howdoi/documents/iacompform_053112.pdf" alt="" target="_blank" rel="noopener noreferrer">a paper form</a> <img src="assets/images/pdf.png" alt="Icon of a PDF file created by Freepik on Flaticon.com." class="icon-pdf" />, and the email address for the <a href="mailto:apdia@muni.org">APD Internal Affairs Unit</a> where you have to send the form.</li>
                  </ul>
                </li>
                <li>Arlington, Texas
                  <ul>
                    <li><a href="https://arlingtontx.gov/city_hall/departments/police/about_us/contact_us/internal_affairs" alt="" target="_blank" rel="noopener noreferrer">Instructions, paper forms, and an online form</a>.</li>
                  </ul>
                </li>
                <li>Atlanta, Georgia
                  <ul>
                    <li><a href="https://www.atlantapd.org/home/showdocument?id=1258" alt="" target="_blank" rel="noopener noreferrer">Instructions</a> <img src="assets/images/pdf.png" alt="Icon of a PDF file created by Freepik on Flaticon.com." class="icon-pdf" />, <a href="https://www.atlantapd.org/services/office-of-professional-standards" alt="" target="_blank" rel="noopener noreferrer">information</a>, and <a href="https://www.atlantapd.org/i-want-to/comment-on-an-officer" alt="" target="_blank" rel="noopener noreferrer">an online form</a>.</li>
                  </ul>
                </li>
                <li>Aurora, Colorado
                  <ul>
                    <li>Online forms to file a <a href="http://cf.auroragov.org/CCAPD/dsp_PoliceComplaintApp.cfm?t=p" alt="" target="_blank" rel="noopener noreferrer">complaint</a> or a <a href="http://cf.auroragov.org/CCAPD/dsp_PoliceComplaintApp.cfm?t=c" alt="" target="_blank" rel="noopener noreferrer">compliment</a>.</li>
                  </ul>
                </li>
                <li>Austin, Texas
                  <ul>
                    <li>The <a href="https://alpha.austin.gov/police-oversight/" alt="" target="_blank" rel="noopener noreferrer">Office of Police Oversight</a> has online forms to file a <a href="https://alpha.austin.gov/en/police-oversight/file-a-complaint-about-an-austin-police-officer/">complaint or a <a href="https://alpha.austin.gov/en/police-oversight/thank-an-austin-police-officer/" alt="" target="_blank" rel="noopener noreferrer">compliment</a> along with <a href="https://alpha.austin.gov/en/police-oversight/official-complaint-and-discipline-documents/#page=1" alt="" target="_blank" rel="noopener noreferrer">previous complaints</a>.</li>
                  </ul>
                </li>
                <li>Bakersfield, California
                  <ul>
                    <li><a href="https://bakersfieldcity.us/gov/depts/police/about_bpd/citizen_complaint_procedure.htm" alt="" target="_blank" rel="noopener noreferrer">Instructions and forms to file a complaint</a> with <a href="https://bakersfieldcity.us/gov/depts/police/about_bpd/department_directory.htm" alt="" target="_blank" rel="noopener noreferrer">compliments going to the Administration Department</a>.</li>
                  </ul>
                </li>
                <li>Baltimore, Maryland
                  <ul>
                    <li>Complaint and compliments can be filed directly with the police to <a href="https://www.baltimorepolice.org/public-integrity-bureau-make-misconduct-complaint" alt="" target="_blank" rel="noopener noreferrer">the Public Integrity Bureau</a> or directly with the city to the <a href="https://civilrights.baltimorecity.gov/civilian-review-board" alt="" target="_blank" rel="noopener noreferrer">Civilian Review Board</a>.</li>
                  </ul>
                </li>
                <li>Baton Rouge, Louisiana
                  <ul>
                    <li><a href="https://www.brla.gov/1821/Complaint-Form" alt="" target="_blank" rel="noopener noreferrer">Instructions and an online form</a>.</li>
                  </ul>
                </li>
                <li>Birmingham, Alabama
                  <ul>
                    <li>Contact <a href="https://police.birminghamal.gov/contacts/" alt="" target="_blank" rel="noopener noreferrer">Internal Affairs</a> for instructions to file complaints and compliments.</li>
                  </ul>
                </li>
                <li>Boston, Massachusetts
                  <ul>
                    <li>Use the online form for <a href="https://bpdnews.com/commend-an-officer-1" alt="" target="_blank" rel="noopener noreferrer">complaints</a> and <a href="https://bpdnews.com/commend-an-officer" alt="" target="_blank" rel="noopener noreferrer">compliments</a>.</li>
                  </ul>
                </li>
                <li>Buffalo, New York
                  <ul>
                    <li><a href="http://www.bpdny.org/158/Complaint-Process" alt="" target="_blank" rel="noopener noreferrer">Instructions and contact information</a>.</li>
                  </ul>
                </li>
                <li>Chandler, Arizona
                  <ul>
                    <li>Use the online forms for <a href="https://www.chandlerpd.com/complaint/" alt="" target="_blank" rel="noopener noreferrer">complaints</a> and <a href="https://www.chandlerpd.com/commendation/" alt="" target="_blank" rel="noopener noreferrer">compliments</a>.</li>
                  </ul>
                </li>
                <li>Charlotte-Mecklenburg, North Carolina
                  <ul>
                    <li><a href="https://charlottenc.gov/CMPD/Pages/Commendation-Complaint_Process.aspx" alt="" target="_blank" rel="noopener noreferrer">Information</a> and links to online forms to file <a href="https://charlottenc.seamlessdocs.com/f/Misconduct" alt="" target="_blank" rel="noopener noreferrer">complaints</a> and <a href="https://charlottenc.seamlessdocs.com/f/Commend" alt="" target="_blank" rel="noopener noreferrer">compliments</a>.</li>
                  </ul>
                </li>
                <li>Chesapeake, Virginia
                  <ul>
                    <li><a href="http://www.cityofchesapeake.net/Assets/documents/departments/police/downloads/Ethics_and_Conduct_Pamphlet.pdf" alt="" target="_blank" rel="noopener noreferrer">Information and instructions</a> <img src="assets/images/pdf.png" alt="Icon of a PDF file created by Freepik on Flaticon.com." class="icon-pdf" />.</li>
                  </ul>
                </li>
                <li>Chicago, Illinois
                  <ul>
                    <li>Instructions, information, and online forms for <a href="https://www.chicagocopa.org/complaints/" alt="" target="_blank" rel="noopener noreferrer">complaints</a> and <a href="https://www.chicagocopa.org/compliment-an-officer/" alt="" target="_blank" rel="noopener noreferrer">compliments</a>.</li>
                  </ul>
                </li>
                <li>Chula Vista, California
                  <ul>
                    <li><a href="https://www.chulavistaca.gov/departments/police-department/about-us/open-data-initiative/citizen-complaints" alt="" target="_blank" rel="noopener noreferrer">Information</a> and links to online forms to file <a href="https://www.chulavistaca.gov/departments/police-department/service-complaint-form" alt="" target="_blank" rel="noopener noreferrer">complaints</a> and <a href="https://www.chulavistaca.gov/departments/police-department/service-commendation-form" alt="" target="_blank" rel="noopener noreferrer">compliments</a>.</li>
                  </ul>
                </li>
                <li>Cincinnati, Ohio
                  <ul>
                    <li><a href="https://www.cincinnati-oh.gov/police/contact-us/complaint-about-police/" alt="" target="_blank" rel="noopener noreferrer">Information</a> and links to online forms to file <a href="https://www.cincinnati-oh.gov/police/contact-us/complaint-about-police/citizen-complaint-form/" alt="" target="_blank" rel="noopener noreferrer">complaints</a> and <a href="https://www.cincinnati-oh.gov/police/contact-us/send-a-compliment/" alt="" target="_blank" rel="noopener noreferrer">compliments</a>.</li>
                  </ul>
                </li>
                <li>Cleveland, Ohio
                  <ul>
                    <li><a href="https://www.cleveland.police.uk/advice/advice-and-information/c/complaints/" alt="" target="_blank" rel="noopener noreferrer">Instructions, information, and online forms</a>.</li>
                  </ul>
                </li>
                <li>Colorado Springs, Colorado
                  <ul>
                    <li><a href="https://coloradosprings.gov/police-department/page/police-service-concerns-complaints" alt="" target="_blank" rel="noopener noreferrer">Online forms</a>.</li>
                  </ul>
                </li>
                <li>Columbus, Ohio
                  <ul>
                    <li><a href="https://www.columbus.gov/police-complimentcomplaint/" alt="" target="_blank" rel="noopener noreferrer">Instructions, information, and online forms</a>.</li>
                  </ul>
                </li>
                <li>Corpus Christi, Texas
                  <ul>
                    <li><a href="https://www.cctexas.com/departments/police-department/complain-about-officer" alt="" target="_blank" rel="noopener noreferrer">Instructions and information on how to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Dallas, Texas
                  <ul>
                    <li><a href="https://www.dallaspolice.net/division/internalaffairs/complaint" alt="" target="_blank" rel="noopener noreferrer">Instructions and information on how to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Denver, Colorado (Police and Sheriff Departments)
                  <ul>
                    <li><a href="https://www.denvergov.org/content/denvergov/en/police-department/contact/complaint-or-commendation.html" alt="" target="_blank" rel="noopener noreferrer">Information and an online form for complaints and compliments</a>.</li>
                  </ul>
                </li>
                <li>Detroit, Michigan
                  <ul>
                    <li><a href="https://detroitmi.gov/government/boards/board-police-commissioners/office-chief-investigator-police-complaints" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Durham, North Carolina
                  <ul>
                    <li><a href="https://durhamnc.gov/180/Internal-Affairs-Unit" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>El Paso, Texas
                  <ul>
                    <li><a href="http://www.elpasotexas.gov/police-department/internal-affairs" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Fort Wayne, Indiana
                  <ul>
                    <li><a href="http://www.fwpd.org/inside-the-fwpd/internal-affairs/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Fort Worth, Texas
                  <ul>
                    <li><a href="https://police.fortworthtexas.gov/Support/internal-affairs" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Fremont, California
                  <ul>
                    <li><a href="https://www.fremontpolice.gov/about-us/transparency-portal/professional-standards-and-accountability" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Fresno, California
                  <ul>
                    <li><a href="https://www.fresno.gov/police/services-special-units/internal-affairs/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Garland, Texas
                  <ul>
                    <li><a href="https://garlandtx.gov/386/Complaints" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Glendale, Arizona
                  <ul>
                    <li><a href="https://glendaleaz.com/live/city_services/public_safety/police_department/reporting/complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Glendale, California
                  <ul>
                    <li><a href="https://www.glendaleca.gov/government/departments/police-department/commendation-complaint-forms" alt="" target="_blank" rel="noopener noreferrer">Online forms to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Greensboro, North Carolina
                  <ul>
                    <li><a href="https://www.greensboro-nc.gov/departments/police/how-are-we-doing" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Henderson, Nevada
                  <ul>
                    <li><a href="https://www.aclunv.org/en/how-file-complaint-law-enforcement-agency-nevada#henderson" alt="" target="_blank" rel="noopener noreferrer">ACLU Nevada's website with information and instructions on how to file a complaint (Henderson does not have an online presence for their Internal Affairs Office)</a>.</li>
                  </ul>
                </li>
                <li>Honolulu, Hawaii
                  <ul>
                    <li><a href="http://www.honolulupd.org/information/index/?page=complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Houston, Texas
                  <ul>
                    <li><a href="http://www.houstontx.gov/police/contact/iad.htm" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Indianapolis, Indiana
                  <ul>
                    <li><a href="https://www.indy.gov/activity/file-impd-complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Irvine, California
                  <ul>
                    <li><a href="https://www.cityofirvine.org/content/what-should-i-do-if-i-want-make-complaint-regarding-officer-who-issued-citation" alt="" target="_blank" rel="noopener noreferrer">Instructions on how to file a complaint</a> (the parking enforcement page is the only source of information on how to file a complaint, apologies for any confusion!).</li>
                  </ul>
                </li>
                <li>Irving, Texas
                  <ul>
                    <li><a href="https://www.cityofirving.org/901/Professional-Standards-Unit" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Jacksonville, Florida
                  <ul>
                    <li><a href="https://www.jaxsheriff.org/Resources/compliments-complaints.aspx" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Jersey City, New Jersey
                  <ul>
                    <li><a href="https://jerseycitynj.gov/cityhall/publicsafety/police/internalaffairs" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Kansas City, Missouri
                  <ul>
                    <li><a href="https://www.kcpd.org/transparency/office-of-community-complaints/where-to-file-a-complaint/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Laredo, Texas
                  <ul>
                    <li><a href="http://www.laredopd.com/administration/" alt="" target="_blank" rel="noopener noreferrer">Information to contact the Office of Professional Standards to file a complaint</a> and <a href="http://www.laredopd.com/commend-an-officer/" alt="" target="_blank" rel="noopener noreferrer">an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Las Vegas, Nevada
                  <ul>
                    <li><a href="https://www.lvmpd.com/en-us/Pages/InternalAffairs-Complaints.aspx" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Lexington, Kentucky
                  <ul>
                    <li><a href="https://www.lexingtonky.gov/public-integrity-unit" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a phone number to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Lincoln, Nebraska
                  <ul>
                    <li><a href="https://www.lincoln.ne.gov/city/police/stats/internalaffairs.htm" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Lincoln, Rhode Island
                  <ul>
                    <li><a href="https://lincolnpoliceri.com/Complaint.pdf" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint</a>. <img src="assets/images/pdf.png" alt="Icon of a PDF file created by Freepik on Flaticon.com." class="icon-pdf" /></li>
                  </ul>
                </li>
                <li>Long Beach, California
                  <ul>
                    <li><a href="http://www.longbeach.gov/Police/Contact-Us/Citizen-Complaint-Procedure/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Los Angeles, California
                  <ul>
                    <li><a href="http://www.lapdonline.org/our_communities/content_basic_view/9217" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Louisville, Kentucky
                  <ul>
                    <li><a href="https://ky-louisvillemetropd.civicplus.com/447/Formal-Complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Lubbock, Texas
                  <ul>
                    <li><a href="https://ci.lubbock.tx.us/departments/police-department/reports-and-forms/file-a-complaint-or-commendation" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Madison, Wisconsin
                  <ul>
                    <li><a href="https://www.cityofmadison.com/police/chief/professionalstandards.cfm" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Memphis, Tennessee
                  <ul>
                    <li><a href="https://www.memphistn.gov/government/police_department/complaints_internal_affairs" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a phone number to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Mesa, Arizona
                  <ul>
                    <li>Information, instructions, and an online form to <a href="https://www.mesaaz.gov/residents/police/units-divisions/professional-standards/the-complaint-process" alt="" target="_blank" rel="noopener noreferrer">file a complaint</a> and <a href="https://www.mesaaz.gov/residents/police/units-divisions/professional-standards/commend-an-employee" alt="" target="_blank" rel="noopener noreferrer">a compliment</a>.</li>
                  </ul>
                </li>
                <li>Nashville, Tennessee
                  <ul>
                    <li><a href="https://www.nashville.gov/Community-Oversight/Complaints-and-Commendations/Police-Complaint-Form.aspx" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Miami, Florida
                  <ul>
                    <li>Information, instructions, and an online form to <a href="https://www.miami-police.org/internal_affairs.html" alt="" target="_blank" rel="noopener noreferrer">file a complaint</a> and <a href="https://www.miami-police.org/incident_reporting2.html?qaframe=(S(qg2hnadbcxlzcokvz3tm3fed))%2FRequestOpen.aspx%3Frqst%3D38%26anon%3D1" alt="" target="_blank" rel="noopener noreferrer">a compliment</a>.</li>
                  </ul>
                </li>
                <li>Miami-Dade County, Florida
                  <ul>
                    <li><a href="https://www8.miamidade.gov/global/police/about-professional-compliance-bureau.page" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and contact information to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Milwaukee, Wisconsin
                  <ul>
                    <li><a href="https://city.milwaukee.gov/fpc/Complaints" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Minneapolis, Minnesota
                  <ul>
                    <li>Online forms to file <a href="http://www.ci.minneapolis.mn.us/police/opcr-complaint" alt="" target="_blank" rel="noopener noreferrer">a complaint</a> or <a href="http://www.ci.minneapolis.mn.us/police/commendation" alt="" target="_blank" rel="noopener noreferrer">a compliment</a>.</li>
                  </ul>
                </li>
                <li>Newark, New Jersey
                  <ul>
                    <li><a href="https://npd.newarkpublicsafety.org/professionalstandards/cap" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>New York City, New York
                  <ul>
                    <li><a href="https://www1.nyc.gov/site/ccrb/complaints/complaints.page" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Norfolk, Virginia
                  <ul>
                    <li><a href="https://www.norfolk.gov/378/Office-of-Professional-Standards" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>North Las Vegas, Nevada
                  <ul>
                    <li><a href="https://www.aclunv.org/en/how-file-complaint-law-enforcement-agency-nevada#nlv" alt="" target="_blank" rel="noopener noreferrer">ACLU Nevada's website with information and instructions on how to file a complaint (North Las Vegas does not have an online presence for their Internal Affairs Office)</a>.</li>
                  </ul>
                </li>
                <li>Oakland, California
                  <ul>
                    <li><a href="https://www.oaklandca.gov/services/report-police-misconduct" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a link to an app as well as an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Oklahoma City, Oklahoma
                  <ul>
                    <li><a href="https://www.okc.gov/departments/police/contact-us" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Omaha, Nebraska
                  <ul>
                    <li>Information, instructions, and a <a href="https://police.cityofomaha.org/images/OPD_Form_80_-_Citizen_Complaint_Form.pdf" alt="" target="_blank" rel="noopener noreferrer">paper form to file a complaint</a> <img src="assets/images/pdf.png" alt="Icon of a PDF file created by Freepik on Flaticon.com." class="icon-pdf" /> or an <a href="https://police.cityofomaha.org/commend-an-officer" alt="" target="_blank" rel="noopener noreferrer">online form to file a compliment</a>.</li>
                  </ul>
                </li>
                <li>Orlando, Florida
                  <ul>
                    <li><a href="http://www.cityoforlando.net/police/internal-affairs/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Philadelphia, Pennsylvania
                  <ul>
                    <li><a href="https://www.phillypolice.com/forms/official-complaint-form/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Phoenix, Arizona
                  <ul>
                    <li><a href="https://www.phoenix.gov/police/commendation-complaint-form" alt="" target="_blank" rel="noopener noreferrer">An online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Pittsburgh, Pennsylvania
                  <ul>
                    <li><a href="https://cprbpgh.org/about/filing-a-complaint/file-a-complaint-now" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Plano, Texas
                  <ul>
                    <li><a href="https://www.plano.gov/884/Compliment-Complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, a paper form to file a complaint, and an online form to file a compliment</a>.</li>
                  </ul>
                </li>
                <li>Portland, Oregon
                  <ul>
                    <li><a href="https://www.portlandoregon.gov/ipr/42860" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Raleigh, North Carolina
                  <ul>
                    <li><a href="https://raleighnc.gov/services/safety/internal-affairs-unit" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Reno, Nevada
                  <ul>
                    <li><a href="https://renopd.com/IA" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Riverside, California
                  <ul>
                    <li><a href="https://www.riversideca.gov/rpd/resources-forms/online-complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Rochester, New York
                  <ul>
                    <li><a href="https://www.cityofrochester.gov/article.aspx?id=8589936552" alt="" target="_blank" rel="noopener noreferrer">Information and instructions to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Sacramento, California
                  <ul>
                    <li><a href="https://www.cityofsacramento.org/Police/Contact/Personnel-Complaint" alt="" target="_blank" rel="noopener noreferrer">Information and instructions to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>San Antonio, Texas
                  <ul>
                    <li><a href="https://www.sanantonio.gov/SAPD/Internal-Affairs" alt="" target="_blank" rel="noopener noreferrer">Information and instructions to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>San Bernardino, California
                  <ul>
                    <li>Unable to find a process online, contact the <a href="http://www.ci.san-bernardino.ca.us/cityhall/police_department/about_sbpd/the_divisions/default.asp" alt="" target="_blank" rel="noopener noreferrer">Administrative Services Division</a> by phone.</li>
                  </ul>
                </li>
                <li>San Diego, California
                  <ul>
                    <li><a href="https://www.sandiego.gov/police/services/officercomments" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>San Francisco, California
                  <ul>
                    <li><a href="https://sfdpa.secure.force.com/apex/VisualAntidote__HostedFastForm?h=14I22" alt="" target="_blank" rel="noopener noreferrer">An online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>San Jose, California
                  <ul>
                    <li><a href="https://www.sanjoseca.gov/your-government/appointees/independent-police-auditor/filing-a-complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Santa Ana, California
                  <ul>
                    <li><a href="https://www.santa-ana.org/pd/location-hours-information/forms" alt="" target="_blank" rel="noopener noreferrer">Instructions and paper forms to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Santa Monica, California
                  <ul>
                    <li><a href="https://santamonicapd.org/pdform.aspx?ekfrm=6610" alt="" target="_blank" rel="noopener noreferrer">An online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Scottsdale, Arizona
                  <ul>
                    <li><a href="https://www.scottsdaleaz.gov/police/police-chief-alan-rodbell/department-of-internal-affairs" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Seattle, Washington
                  <ul>
                    <li><a href="http://www.seattle.gov/opa/complaints/file-a-complaint" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Spokane, Washington
                  <ul>
                    <li>City Police: <a href="https://my.spokanecity.org/opo/forms/online/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                    <li>County Sheriff: <a href="https://www.spokanecounty.org/DocumentCenter/View/3955/Complaint-Form-PDF?bidId=" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>St. Louis, Missouri
                  <ul>
                    <li><a href="https://www.stlouis-mo.gov/government/departments/public-safety/civilian-oversight-board/complaint-process.cfm" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>St. Paul, Minnesota
                  <ul>
                    <li><a href="https://www.stpaul.gov/departments/human-rights-equal-economic-opportunity/police-civilian-internal-affairs-review-0" alt="" target="_blank" rel="noopener noreferrer">An online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>St. Petersburg, Florida
                  <ul>
                    <li>Information, instructions, and an online form to submit a <a href="http://police.stpete.org/employee-complaint/index.html" alt="" target="_blank" rel="noopener noreferrer">complaint</a> or a <a href="http://police.stpete.org/cache/employee-recognition/index.html" alt="" target="_blank" rel="noopener noreferrer">compliment</a>.</li>
                  </ul>
                </li>
                <li>Stockton, California
                  <ul>
                    <li><a href="http://ww1.stocktonca.gov/Departments/Police/Contact-Us/Provide-Feedback" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and a paper form to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Tampa, Florida
                  <ul>
                    <li><a href="https://www.tampagov.net/police/professional-standards-bureau" alt="" target="_blank" rel="noopener noreferrer">Information and instructions to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Toledo, Ohio
                  <ul>
                    <li>Information, instructions, and a phone number to file a <a href="https://www.toledopolice.com/online-2/accident-reports-7.html" alt="" target="_blank" rel="noopener noreferrer">complaint</a> and an online form to file a <a href="https://www.toledopolice.com/online-2/send-a-compliment.html" alt="" target="_blank" rel="noopener noreferrer">compliment</a>.</li>
                  </ul>
                </li>
                <li>Tucson, Arizona
                  <ul>
                    <li>Online forms to file a <a href="https://www.tucsonaz.gov/police/complaints" alt="" target="_blank" rel="noopener noreferrer">complaint</a> and a <a href="https://www.tucsonaz.gov/police/compliments" alt="" target="_blank" rel="noopener noreferrer">compliment</a>.</li>
                  </ul>
                </li>
                <li>Tulsa, Oklahoma
                  <ul>
                    <li><a href="https://www.tulsapolice.org/content/internalaffairs.aspx" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint and compliment</a>.</li>
                  </ul>
                </li>
                <li>Virginia Beach, Virginia
                  <ul>
                    <li><a href="https://www.vbgov.com/government/departments/police/profstanddiv/Pages/ia-faqs.aspx" alt="" target="_blank" rel="noopener noreferrer">Information and instructions to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Washington, DC
                  <ul>
                    <li><a href="https://policecomplaints.dc.gov/" alt="" target="_blank" rel="noopener noreferrer">Information, instructions, and an online form to file a complaint</a>.</li>
                  </ul>
                </li>
                <li>Wichita, Kansas
                  <ul>
                    <li><a href="https://www.wichita.gov/WPD/Pages/ProfessionalStandards.aspx" alt="" target="_blank" rel="noopener noreferrer">Information and instructions to file a complaint or compliment</a>.</li>
                  </ul>
                </li>
                <li>Winston-Salem, North Carolina
                  <ul>
                    <li><a href="https://www.cityofws.org/461/Filing-a-Complaint" alt="" target="_blank" rel="noopener noreferrer">Information and instructions to file a complaint</a>.</li>
                  </ul>
                </li>
                <!-- Start template
                <li>CITY
                  <ul>
                    <li><a href="URL" alt="" target="_blank" rel="noopener noreferrer">TEXT</a>.</li>
                  </ul>
                </li>
                End template -->
              </ul>
            </p>
            
            <!-- Why this matters -->
            <h2 id="why-this-matters">Why should this matter to you?</h2>
            <p>There are <a href="https://project.wnyc.org/disciplinary-records/" alt="WNYC's analysis on public records law applicability to police disciplinary records." alt="" target="_blank" rel="noopener noreferrer">only 12 states in the entire country</a> that make police disciplinary records generally available to the public. This is a double-edged sword, meaning many of the cops who are complimented by their community won't be heard from as well, leaving examples of good cops to the whims of the city or department's social media team.</p>
            <p>Making sure the general public knows which cops are good and which ones aren't will ensure that the practice of moving one town over to continue a career never happens again, while also promoting a practice of promoting those who truly serve the community from within.</p>
          </main>
        </div>
      </div>
    </div>
    
    <!-- Fin! -->
    <?php
      include("assets/includes/footer.inc");
      include("assets/includes/scripts.inc");
    ?>
  </body>
</html>
