<?php
set_include_path( get_include_path() . PATH_SEPARATOR . $_SERVER['DOCUMENT_ROOT'] );
date_default_timezone_set('America/Detroit');
?>

<!doctype html>
<html lang="en-US">
  <!-- generated by uswds@2.7.0 -->
  <head>
    <?php
      include("assets/includes/meta.inc");
    ?>
    <title>Register to vote and be heard</title>
    <?php
      include("assets/includes/css.inc");
    ?>
  </head>
  <body>

    <?php
      include("assets/includes/banner.inc");
      include("assets/includes/header-info.inc");
    ?>
    
    <!-- Beginning -->
    <div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          
          <!-- Side Nav -->
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>">Home</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>new-contracts/" class="">New Contracts</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>register-to-vote/" class="">Register To Vote</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>report-all-cops/" class="">Report All Cops</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>resources/" class="usa-current">Resources</a>
                  <ul class="usa-sidenav__sublist">
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>resources/">Stand with Giants</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>resources/#steps-for-success">LOPC steps for success</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>resources/#inspiration">Read and learn more</a></li>
                  </ul>
                </li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>support/" class="">Support</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>join/" class="">Join your Local OPC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>contact/" class="">Contact us</a></li>
              </ul>
            </nav>
          </div>
          
          <!-- Main -->
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1 id="stand-with-giants">Stand on the shoulders of giants</h1>
            <p class="usa-intro">Use all the experience of those who came before you.</p>
            
            <!-- Local OPC practices -->
            <h2 id="steps-for-success">Make your Local OPC effective</h2>
            <p>These are the steps we believe will help you be successful. As always, we <a href="contact/" alt="">welcome feedback</a> on how we can improve this information for everyone who wants to use it.</p>
            <!-- Step 1 -->
            <h3>Step 1: Identify the problem</h3>
            <p>What is that has brought you and your community together to start a Local OPC? Is it how your community investigates misconduct complaints as well as how they promote professional compliments? Is it related to the tax burden associated with paying for judgments against your community when a victim of a misconduct wins a court case or settles for compensation? Is there a use of force policy that has to be followed and does it need to be updated? These are examples of the types of problems a Local OPC can resolve.</p>
            <p>One of the most successful ways a Local OPC can settle, as a community, on the problem they are trying to solve, is to apply design thinking to the issue. 18F, a federal government organization that is focused on providing better access to digital services and resources, has created a <a href="https://methods.18f.gov/" alt="" target="_blank" rel="noopener noreferrer">useful set of Methods</a> that can be adapted to the work a Local OPC. In particular, using the Fundamentals to identify a problem that everyone can rally behind will be much easier when you combine it with the Discovery and Decide Methods.</p>
            <!-- Step 2 -->
            <h3>Step 2: Build your coalition</h3>
            <p>Once a team has settled on a problem or problems that they'd like to solve, it is important to find out who else in the community feels the same way and would be willing to support a Local OPC's efforts. Additionally, it will provide an opportunity to gain feedback from other members of the community, ensuring the message being championed by a Local OPC is one that everyone can get behind. To be successful, there are two key actions that a Local OPC can take: identify the right partners and identify the right tools.</p>
            <h4>Identify the right partners</h4>
            <p>Every single person is impacted by a police force that operates within the community where they live. This is especially true for people of color, as <a href="http://www.rob-gillezeau.com/research.html" alt="" target="_blank" rel="noopener noreferrer">research is showing</a> a group of our fellow citizens have seemingly been <a href="https://www.npr.org/transcripts/871298161" alt="" target="_blank" rel="noopener noreferrer">subject to increased violence at the hands of police</a> since the advent of the unionization of law enforcement agencies. This means there is someone in your community who has worked either on your exact problem or something like it before. Find them and see what they learned. Also, talk about working together to continue their efforts that align with your own.</p>
            <p>Whether a religious institution, a local branch of a national organization dedicated to supporting a particular group that lives within your community, or even local charities and corporations, there will be other groups made up of members of your community that would be happy to participate in your Local OPC's activities. We would be happy help you find them, get in touch with the right people, and build bonds across the various viewpoints in your community.</p>
            <h4>Identify the right tools</h4>
            <p>Collaboration and communication is key and we recommend using tools like these to allow for both to happen across your entire team. Ensuring everyone knows what to use and when to use it will be essential to making sure the organization can operate organically, without the need for any particular individuals.</p>
            <p>
              <ul>
                <li>Slack, Google Hangouts/Meet, or Microsoft Teams - Communicate with your team, including over video</li>
                <li>Twitter and Facebook - Share general posts that impact our community</li>
                <li>YouTube and Instagram - Share general videos that impact our community</li>
                <li>NextDoor.com - Share specific information that impacts our community</li>
                <li>US Web Design Standards - Create accessible and easy to use websites</li>
                <li>MeetUp.com - Attract members of the community to attend LOPC events</li>
                <li>Google Suite - Collaborate on documents, spreadsheets, presentations, and forms</li>
                <li>GitHub - Share everything we develop, from documents to applications</li>
              </ul>
            </p>
            <p>If you need help setting up accounts with any of these platforms for your Local OPC, all you have to do is let us know, and we'll be there to help as soon as we can!</p>
            <!-- Step 3 -->
            <h3>Step 3: Set goals</h3>
            <p>Once you've identified your problem, built alliances within the community, and organized yourselves to take action, discuss what it is your team will have to do to make sure you can solve the problem you've identified, using the resources on hand. Do you want to change a law? Do you want to amend a clause or provision in an existing contract or regulation? Maybe you want to include more people from the community in the boards, committees, and other groups that make key decisions in your community? Determine what you want to do, make sure everyone - including your allies who are committed to working with you - are in agreement, and make it official. Develop a plan that will help you move, step by step, towards success, and make sure you allow for enough flexibility to pivot as you learn new things. We try to share our goals as broadly as we can, but don't hesitate to reach out if you think we can help setting up goals you can rally behind.</p>
            <!-- Step 4 -->
            <h3>Step 4: Gather information</h3>
            <p>Learn new things and adapting to account for that knowledge is what makes an idea become a reality. Taking the ideal solution and making it a practical solution requires incorporating new information into your actions. Not only will you have to find out who is involved with each step you have to take going forward, but how they work, what rules they have to follow, and when you can meet with them to push things forward in an official and actionable way. This is an area where our team excels - gathering information - so please ask for help if you need it.</p>
            <!-- Step 5 -->
            <h3>Step 5: Build a campaign</h3>
            <p>Using the information you've gathered, use the remaining 18F Methods under Make and Validate to ensure you've developed a functional plan, with realistic tasks, that will result in documents or actions that will actually allow you to achieve the objectives your Local OPC has set out. This is one of the steps that will almost always be unique to a community's circumstances, but there is much that can be learned from the activities other Local OPC teams have undertaken. Feel free to run your ideas by other Local OPCs to work out as many kinks as you can.</p>
            <!-- Step 6 -->
            <h3>Step 6: Engage your Stakeholders and your Targets</h3>
            <p>With a strategy in place, you can begin the work of engaging with key stakeholders, including Local OPC and allied community organization leadership, as well as decision makers in the official power structure in your community. Some people will have to target their councilmembers, others their mayor, some will have to focus on the voters themselves. Based on your unique situation, a Local OPC can help you organize and formalize your communication plan and make sure you effectively advocate for the actions your community will have to undertake in order to successfully achieve the goals you have agreed upon.</p>
            <!-- Step 7 -->
            <h3>Step 7: Evaluate the impact of your campaign</h3>
            <p>Metrics and indicators can be established to show how successful your efforts have been each step of the way. These data points are not only useful for improving your Local OPC's efforts, but also every effort in this realm as a whole. Seeing what works and what doesn't in each particular scenario will make sure every lesson learned is passed on and every new Local OPC starts stronger than the one that came before it.</p>
            <p>This process will also help you get ready for the next round of work after you change the existing police union contract to reflect your community's needs. Who is selling equipment to the police right now? Are those companies involved in political campaigns? What was the evaluation process behind those contracts to ensure there is no conflict of interest?</p>
            <p>These are questions that you can ask for the next round of problems you solve now that you've gotten the hang of how your community's government works. We are in this together, so make use of the information we have collected and let's work together to make things better for everyone!</p>
            
            <!-- Learn more -->
            <h2 id="inspiration">Be inspired; learn more</h2>
            <p>
              We encourage everyone to read and learn from the following articles, guides, and websites:
              <ul>
                <li><a href="https://medium.com/@BarackObama/how-to-make-this-moment-the-turning-point-for-real-change-9fa209806067" alt="" target="_blank" rel="noopener noreferrer">How to Make this Moment the Turning Point for Real Change - Barack Obama</a></li>
                <li><a href="https://www.obama.org/anguish-and-action/" alt="" target="_blank" rel="noopener noreferrer">Anguish and Action - The Obama Foundation</a></li>
                <li><a href="https://www.obama.org/wp-content/uploads/Toolkit.pdf" alt="" target="_blank" rel="noopener noreferrer">New Era of Public Safety: An advocacy toolkit for fair, safe, and effective community policing - The Obama Foundation</a> <img src="assets/images/pdf.png" alt="Icon of a PDF file created by Freepik on Flaticon.com." class="icon-pdf" /></li>
            </p>
          </main>
        </div>
      </div>
    </div>
    
    <!-- Fin! -->
    <?php
      include("assets/includes/footer.inc");
      include("assets/includes/scripts.inc");
    ?>
  </body>
</html>
