<?php
set_include_path( get_include_path() . PATH_SEPARATOR . $_SERVER['DOCUMENT_ROOT'] );
date_default_timezone_set('America/Detroit');
?>

<!doctype html>
<html lang="en-US">
  <!-- generated by uswds@2.7.0 -->
  <head>
    <?php
      include("assets/includes/meta.inc");
    ?>
    <title>Support charitable charities</title>
    <?php
      include("assets/includes/css.inc");
    ?>
  </head>
  <body>

    <?php
      include("assets/includes/banner.inc");
      include("assets/includes/header-info.inc");
    ?>
    
    <!-- Beginning -->
    <div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          
          <!-- Side Nav -->
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>">Home</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>new-contracts/" class="">New Contracts</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>register-to-vote/" class="">Register To Vote</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>report-all-cops/" class="">Report All Cops</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>resources/" class="">Resources</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>support/" class="usa-current">Support</a>
                  <ul class="usa-sidenav__sublist">
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>support/">Choose who you support</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>support/#charity">Charities that work</a></li>
                    <li class="usa-sidenav__item"><a href="<?php echo $path;?>support/#legislation">Legislation that works</a></li>
                  </ul>
                </li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>join/" class="">Join your Local OPC</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>contact/" class="">Contact us</a></li>
              </ul>
            </nav>
          </div>
          
          <!-- Main -->
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Support good causes</h1>
            <p class="usa-intro">Give to those who actually give back.</p>
            
            <!-- Charitable charities -->
            <h2 id="charity">Charitable charities</h2>
            <p>Not every charitable dollar is created equally! The following organizations, listed in alphabetical order, are ones that are relevant, have filed taxes for 2018 if not 2019, and have received at least a 80 out of 100 from Charity Navigator using <a href="https://www.charitynavigator.org/index.cfm?bay=content.view&cpid=5593" alt="" target="_blank" rel="noopener noreferrer">their robust methodology</a>.</p>
            <p>
              <ul>
                <li><a href="https://www.aclu.org/" alt="The official page for American Civil Liberties Union Foundation." target="_blank" rel="noopener noreferrer">American Civil Liberties Union Foundation</a> - <a href="https://action.aclu.org/give/now?ms_aff=NAT&initms_aff=NAT&ms=web_horiz_nav_hp&initms=web_horiz_nav_hp&ms_chan=web&initms_chan=web&redirect=node/65102" alt="The official donation page for  American Civil Liberties Union Foundation" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=3247" alt="The Charity Navigator page for  American Civil Liberties Union Foundation." target="_blank" rel="noopener noreferrer">92.02.00/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=1323892&ein=133871360&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=13-3871360&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="The IRS page that contains links to financial information submitted by American Civil Liberties Union Foundation." target="_blank" rel="noopener noreferrer">Form 990</a></li>
                <li><a href="https://www.amnestyusa.org/" alt="" target="_blank" rel="noopener noreferrer">Amnesty International USA</a> - <a href="https://donate.amnestyusa.org/page/57973/donate/1?ea.tracking.id=closed-redirected" alt="" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=3294" alt="" target="_blank" rel="noopener noreferrer">87.73/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=4147834&ein=520851555&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=52-0851555&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="" target="_blank" rel="noopener noreferrer">Form 990</a></li>
                <li><a href="https://www.adl.org/" alt="" target="_blank" rel="noopener noreferrer">Anti-Defamation League</a> - <a href="https://support.adl.org/give/174715/#!/donation/checkout" alt="" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=10657" alt="" target="_blank" rel="noopener noreferrer">84.64/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=1322691&ein=131818723&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=13-1818723&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="" target="_blank" rel="noopener noreferrer">Form 990</a></li>
                <li><a href="https://www.advancingjustice-aajc.org/" alt="" target="_blank" rel="noopener noreferrer">Asian Americans Advancing Justice - AAJC Inc.</a> - <a href="https://secure.donationpay.org/aajc/" alt="" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=16353" alt="" target="_blank" rel="noopener noreferrer">92.45/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=1221404&ein=133619000&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=13-3619000&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="" target="_blank" rel="noopener noreferrer">Form 990</a></li>
                <li><a href="https://ccrjustice.org/" alt="" target="_blank" rel="noopener noreferrer">Center for Constitutional Rights</a> - <a href="https://ccrjustice.org/donate?track1=website&track2=wheader&track3=2016-DEC-16" alt="" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=7728" alt="" target="_blank" rel="noopener noreferrer">91.62/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=618530&ein=226082880&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=22-6082880&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="" target="_blank" rel="noopener noreferrer">Form 990</a></li>
                <li><a href="https://www.clasp.org/" alt="" target="_blank" rel="noopener noreferrer">Center for Law and Social Policy - CLASP</a> - <a href="https://www.clasp.org/support-clasp" alt="" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=9420" alt="" target="_blank" rel="noopener noreferrer">96.66/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=1226808&ein=237000150&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=23-7000150&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="" target="_blank" rel="noopener noreferrer">Form 990</a></li>
                <li><a href="https://eji.org/" alt="" target="_blank" rel="noopener noreferrer">Equal Justice Initiative</a> - <a href="https://support.eji.org/give/153413/#!/donation/checkout" alt="" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=12756" alt="" target="_blank" rel="noopener noreferrer">100.00/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=771691&ein=631135091&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=63-1135091&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="" target="_blank" rel="noopener noreferrer">Form 990</a></li>
                <li><a href="https://headwatersfoundation.org/" alt="The official page for Headwaters Foundation for Justice." target="_blank" rel="noopener noreferrer">Headwaters Foundation for Justice</a> - <a href="https://headwatersfoundation.org/give" alt="The official donation page for Headwaters Foundation for Justice" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="https://www.charitynavigator.org/index.cfm?bay=search.summary&orgid=11536" alt="The Charity Navigator page for Headwaters Foundation for Justice." target="_blank" rel="noopener noreferrer">88.8/100</a>; <a href="https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=1356396&ein=363359386&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=36-3359386&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States" alt="The IRS page that contains links to financial information submitted by Headwaters Foundation for Justice." target="_blank" rel="noopener noreferrer">Form 990</a></li>
                Institute for Free Speech
                LatinoJustice PRLDEF
                Leadership Conference Education Fund
                Mexican American Legal Defense and Educational Fund
                Minority Corporate Counsel Association
                Muslim Advocates
                NAACP Legal Defense and Educational Fund
                National Association for the Advancement of Colored People
                National Black Child Development Institute
                National Center for Law and Economic Justice
                National Urban League
                People's Action Institute
                Public Advocates
                Public Justice Center
                Race Forward
                Southern Poverty Law Center
                UnidosUS
                <!-- Start Template
                <li><a href="URL" alt="" target="_blank" rel="noopener noreferrer">CHARITY</a> - <a href="URL" alt="" target="_blank" rel="noopener noreferrer">Donate</a>; <a href="URL" alt="" target="_blank" rel="noopener noreferrer">X/100</a>; <a href="URL" alt="" target="_blank" rel="noopener noreferrer">Form 990</a></li>
                End Template -->
              </ul>
            </p>
            
            <!-- Legislation that works -->
            <h2 id="legislation-that-works">Legislation that works</h2>
            <p>Data has proven what works and what doesn't in terms of meaningful legislation. Since 2014, <a href="https://www.joincampaignzero.org/" alt="The official webpage of the Campaign Zero project."  target="_blank" rel="noopener noreferrer">at least 107 new laws</a> have been enacted to address police violence. Review and learn what makes these bills effective and fight to have politicians implement versions of them in your town, city, county, and state.</p>
            <p>
              <ul>
                <li><a href="https://www.lawserver.com/law/state/tennessee/tn-code/tennessee_code_39-11-620" alt="A link to the official language of Tennessee Code 39-11-620." target="_blank" rel="noopener noreferrer">Tennessee Code 39-11-620</a>. Signed into law in 1989. Tennessee's Deadly Force law. One of the only states legally requiring police use every available alternative before shooting. Laws in most other states say police can shoot even if they clearly could've de-escalated or used non-lethal force instead.</li>
                <li><a href="https://www.cga.ct.gov/2015/ACT/PA/2015PA-00004-R00HB-07103SS1-PA.htm" alt="A link to the official language of Connecticut HB 7103." target="_blank" rel="noopener noreferrer">Connecticut HB 7103</a>. Signed into law in 2015. Makes it illegal for police departments to hire officers who were previously fired or who resigned while  being investigated for serious misconduct and/or excessive force.</li>
                <li><a href="https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201520160AB953" alt="A link to the official language of California's AB 953." target="_blank" rel="noopener noreferrer">California AB 953</a>. Signed into law in 2015. Requires every police department report every stop, search, arrest & use of force to a state database. Includes officer ID, location, perceived race, age, gender, gender identity, disability status. Raw data & analysis published yearly.</li>
                <li><a href="https://legiscan.com/MT/text/HB330/id/1198338" alt="A link to the official language of Montana HB 330." target="_blank" rel="noopener noreferrer">Montana HB 330</a>. Signed into law in Montana in 2015. Bans police from receiving military weapons from the federal government including tanks, armored vehicles, drones, grenade launchers, aircraft.</li>
                <li><a href="http://www.leg.state.co.us/clics/clics2016a/csl.nsf/billcontainers/F5A2A727B31083DD87257F45007EDDCE/$FILE/1264_01.pdf" alt="A link to the original language of Colorado HB 12-64." target="_blank" rel="noopener noreferrer">Colorado HB 12-64 (Original language)</a>. While the official language used was signed into law in, 2016, the original version of the bill made it a crime for officers to use chokeholds or any other neck restraint, except if a person posed an imminent threat of death/serious injury. The original is linked to here since the official version was watered down before passing.</li>
                <li><a href="http://ilga.gov/legislation/fulltext.asp?DocName=10000SB0058&GA=100&SessionId=91&DocTypeId=SB&LegID=99371&DocNum=58&GAID=14&Session=&print=true" alt="A link to the official language of Illinois HB 58." target="_blank" rel="noopener noreferrer">Illinois HB 58</a>. Signed into law in 2017. Requires any officer who shoots someone to submit to mandatory drug and alcohol testing within one hour of the shooting.</li>
                <li><a href="https://cao-94612.s3.amazonaws.com/documents/oak062931.pdf" alt="A link to the official language of Oakland's Measure LL." target="_blank" rel="noopener noreferrer">Oakland's Measure LL</a>. Passed in 2016. Creates one of the strongest community oversight structures in the nation. Power to pass department policies, fire officers and the police chief, selects the candidates for police chief, investigates misconduct, among other powers.</li>
                <li><a href="https://nebraskalegislature.gov/FloorDocs/105/PDF/Slip/LB791.pdf" alt="A link to the official language of Nebraska LB 791." target="_blank" rel="noopener noreferrer">Nebraska LB 791</a>. Nebraska LB 791. Signed 2018. Restricts State Patrol's union contract from interfering with police accountability. Should have gone further to ban all police union contracts from having language affecting misconduct investigations, discipline & records.</li>
              </ul>
            </p>
            <p><em>Credit to <a href="https://twitter.com/samswey/status/1266855519425384450" alt="A thread on Twitter with mentions of these bills." target="_blank" rel="noopener noreferrer">Samuel Sinyangwe</a> for this list.</em></p>
          </main>
        </div>
      </div>
    </div>
    
    <!-- Fin! -->
    <?php
      include("assets/includes/footer.inc");
      include("assets/includes/scripts.inc");
    ?>
  </body>
</html>
