<a class="usa-skipnav" href="#main-content">Skip to main content</a>
    <section class="usa-banner" aria-label="The official website for the Local Order of Police and Citizens.">
      <div class="usa-accordion">
        <header class="usa-banner__header">
          <div class="usa-banner__inner">
            <div class="grid-col-auto">
              <img class="usa-banner__header-flag" src="<?php echo $path;?>assets/images/lopc-logo.png" alt="The Local Order of Police and Citizens logo.">
            </div>
            <div class="grid-col-fill tablet:grid-col-auto">
              <p class="usa-banner__header-text">The official website of the Local Order of Police and Citizens</p>
              <p class="usa-banner__header-action" aria-hidden="true">Here’s how you know</p>
            </div>
            <button class="usa-accordion__button usa-banner__button"
              aria-expanded="false" aria-controls="gov-banner">
              <span class="usa-banner__button-text">Here’s how you know</span>
            </button>
          </div>
        </header>
        <div class="usa-banner__content usa-accordion__content" id="gov-banner">
          <div class="grid-row grid-gap-lg">
            <div class="usa-banner__guidance tablet:grid-col-6">
              <img class="usa-banner__icon usa-media-block__img" src="<?php echo $path;?>assets/uswds/img/icon-dot-gov.svg" alt="Dot gov">
              <div class="usa-media-block__body">
                <p>
                  <strong>The LocalOPC.org means it’s official.</strong>
                  <br>
                  If the URL you are visiting is different, it isn't controlled by us. Before sharing any information, make sure you’re on our actual website.
                </p>
              </div>
            </div>
            <div class="usa-banner__guidance tablet:grid-col-6">
              <img class="usa-banner__icon usa-media-block__img" src="<?php echo $path;?>assets/uswds/img/icon-https.svg" alt="Https">
              <div class="usa-media-block__body">
                <p>
                  <strong>The site is secure.</strong>
                  <br>
                  The <strong>https://</strong> ensures that you are connecting to our website and that any information you provide is encrypted and transmitted securely. We use <a href="https://letsencrypt.org/" alt="Let's Encrypt's official website." target="_blank" rel="noopener noreferrer">LetsEncrypt</a>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>