<footer class="usa-footer">
      <div class="grid-container usa-footer__return-to-top">
        <a href="<?php echo $path;?>#">Return to top</a>
      </div>
      <div class="usa-footer__primary-section">
        <nav class="usa-footer__nav" aria-label="Footer navigation">
          <ul class="grid-row grid-gap">
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>" alt="">Home Page</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>new-contracts.php" alt="">New Contracts</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>register-to-vote.php" alt="">Register To Vote</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>report-all-cops.php" alt="">Report All Cops</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>resources.php" alt="">Resources</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>support.php" alt="">Support</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="https://github.com/LocalOPC/LocalOPC.org" alt="A link to the GitHub repository for this website." target="_blank" rel="noopener noreferrer">Repo</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="usa-footer__secondary-section">
        <div class="grid-container">
          <div class="grid-row grid-gap">
            <div class="usa-footer__logo grid-row mobile-lg:grid-col-6 mobile-lg:grid-gap-2">
              <div class="mobile-lg:grid-col-auto">
                <img class="usa-footer__logo-img footer-circle" src="<?php echo $path;?>assets/images/lopc-logo.png" alt="The Local Order of Police and Citizens logo.">
              </div>
              <div class="mobile-lg:grid-col-auto">
                <h3 class="usa-footer__logo-heading">Local Order of Police and Citizens</h3>
              </div>
            </div>
            <div class="usa-footer__contact-links mobile-lg:grid-col-6">
              <div class="usa-footer__social-links grid-row grid-gap-1">
                <div class="grid-col-auto">
                  <a class="usa-social-link usa-social-link--facebook" href="https://www.facebook.com/Local-Order-of-Police-and-Citizens-127198222357050/" alt="" target="_blank" rel="noopener noreferrer">
                    <span>Facebook</span>
                  </a>
                </div>
                <div class="grid-col-auto">
                  <a class="usa-social-link usa-social-link--twitter" href="https://www.twitter.com/LocalOPC/" alt="" target="_blank" rel="noopener noreferrer">
                    <span>Twitter</span>
                  </a>
                </div>
                <div class="grid-col-auto">
                  <a class="usa-social-link usa-social-link--youtube" href="https://www.youtube.com/channel/UC9mWVulWtL7mGzy_3bM9iqw" alt="" target="_blank" rel="noopener noreferrer">
                    <span>YouTube</span>
                  </a>
                </div>
              </div>
              <h3 class="usa-footer__contact-heading">Contact your Local OPC</h3>
              <address class="usa-footer__address">
                <div class="usa-footer__contact-info grid-row grid-gap">
                  <div class="grid-col-auto">
                    <a href="<?php echo $path;?>join.php" alt="">Join</a>
                  </div>
                  <div class="grid-col-auto">
                    <a href="<?php echo $path;?>contact.php" alt="">Contact</a>
                  </div>
                </div>
              </address>
            </div>
          </div>
        </div>
      </div>
    </footer>