<div class="usa-overlay"></div>
    <header class="usa-header usa-header--basic usa-header--megamenu">
      <div class="usa-nav-container">
        <div class="usa-navbar">
          <div class="usa-logo" id="basic-mega-logo">
            <em class="usa-logo__text"><a href="<?php echo $path;?>/" title="Home" aria-label="Home">Local Order of Police and Citizens</a></em>
          </div>
          <button class="usa-menu-btn">Menu</button>
        </div>
        
        <nav aria-label="Primary navigation" class="usa-nav">
          <button class="usa-nav__close"><img src="<?php echo $path;?>assets/uswds/img/close.svg" alt="close"></button>
          <ul class="usa-nav__primary usa-accordion">
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="<?php echo $path;?>"><span>Home</span></a></li>

            <li class="usa-nav__primary-item">
              <button class="usa-accordion__button usa-nav__link usa-current" aria-expanded="false" aria-controls="basic-mega-nav-section-one"><span>Local OPC's Mission</span></button>
              <div id="basic-mega-nav-section-one" class="usa-nav__submenu usa-megamenu">
                <div class="grid-row grid-gap-4">
                  <div class="usa-col">
                    <ul class="usa-nav__submenu-list">
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>new-contracts/" class="" alt="">New contracts for police</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>new-contracts/#upcoming-renewals" class="" alt="">Upcoming contract renewals</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>new-contracts/#no-contracts" class="" alt="">Police with no contracts</a></li>
                    </ul>
                  </div>
                  <div class="usa-col">
                    <ul class="usa-nav__submenu-list">
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>register-to-vote/" class="" alt="">Register to vote</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>register-to-vote/#register-to-vote" class="" alt="">How to register today</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>register-to-vote/#improve-voting" class="" alt="">Improve access to voting</a></li>
                    </ul>
                  </div>
                  <div class="usa-col">
                    <ul class="usa-nav__submenu-list">
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>report-all-cops/" class="" alt="">Report all cops</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>report-all-cops/#share-everything" class="" alt="">Share the good and the bad</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>report-all-cops/#why-this-matters" class="" alt="">Why this matters to you</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </li>
            
            <li class="usa-nav__primary-item">
              <button class="usa-accordion__button usa-nav__link" aria-expanded="false" aria-controls="basic-mega-nav-section-two"><span>Useful Information</span></button>
              <div id="basic-mega-nav-section-two" class="usa-nav__submenu usa-megamenu">
                <div class="grid-row grid-gap-4">
                  <div class="usa-col">
                    <ul class="usa-nav__submenu-list">
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>resources/" class="" alt="">Resources you can use</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>resources/#steps-for-success" class="" alt="">LOPC steps for success</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>resources/#inspiration" class="" alt="">Read and learn more</a></li>
                    </ul>
                  </div>
                  <div class="usa-col">
                    <ul class="usa-nav__submenu-list">
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>support/" class="" alt="">Choose who you support</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>support/#charity" class="" alt="">Charities that work</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>support/#legislation" class="" alt="">Legislation that works</a></li>
                    </ul>
                  </div>
                  <div class="usa-col">
                    <ul class="usa-nav__submenu-list">
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>join/" class="" alt="">Join your local branch</a></li>
                      <li class="usa-nav__submenu-item"><a href="<?php echo $path;?>contact/" class="" alt="">Contact us</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </nav>
      </div>
    </header>